repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.12.1
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.16.1
    hooks:
      # Run the linter.
      - id: ruff-check
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/astral-sh/ty-pre-commit
    # ty version.
    rev: v0.0.66
    hooks:
      - id: ty
  - repo: local
    hooks:
      - id: pytest-coverage
        name: pytest-coverage
        entry: uv run pytest tests/ --cov=src --cov-branch --cov-fail-under=100
        language: system
        pass_filenames: false
        always_run: true
